# Generated by Django 6.0.1 on 2026-05-18 18:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contractor', 'Contractor')], default='full_time', max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('joining_date', models.DateField()),
                ('skills', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='employee.employee')),
            ],
            options={
                'db_table': 'employees',
                'indexes': [models.Index(fields=['country'], name='idx_employees_country'), models.Index(fields=['job_title'], name='idx_employees_job_title'), models.Index(fields=['department'], name='idx_employees_department'), models.Index(fields=['country', 'job_title'], name='idx_employees_country_title')],
            },
        ),
    ]
